### ISSUE TITLE
Doesn't really seem like the place for april fools pranks

### ISSUE THREAD

**Issue by grastraa** [thomasloven/lovelace-card-mod#189]
Can you not?

**Comment by jayakornk** [comment]
I have been restarting my server for a couple of hour trying to figure out what is going on.
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/42465929/161129774-78736f00-71f1-4e28-9b00-ff93e4e95112.png">

**Comment by thomasloven** [comment]
It seemed like a fun idea.
I was wrong, and I am sorry.

Please update to 3.1.4.

**Comment by genestealer** [comment]
[If your frontend looks weird today Community Post](https://community.home-assistant.io/t/if-your-frontend-looks-weird-today/407225)

**Comment by Sloth-on-meth** [comment]
@grastraa watch your tone. @thomasloven made a funny joke, because it's April fools. We can all use some laughs these days. Get off your high horse and thank him for making card mod, sheesh

**Comment by frznfngrs** [comment]
Entitled pricks complaining about a harmless joke in free software.    Welcome to 2022 I guess

**Comment by susanacf90** [comment]
> Entitled pricks complaining about a harmless joke in free software. Welcome to 2022 I guess

Yup... Imagine if it was an actually harmful action instead of a joke... It was funny though. 😅

**Comment by Sholofly** [comment]
> > Entitled pricks complaining about a harmless joke in free software. Welcome to 2022 I guess
> 
> Yup... Imagine if it was an actually harmful action instead of a joke... It was funny though. 😅

But it wasn't....

**Comment by grastraa** [comment]
Eh, I was annoyed for about 20 minutes till I uncovered it and had a frustrated laughed. Didn't hate the joke, but feel it could have been implemented in a friendlier way. Some users scrapped work, some had performance issues it seems. 

Not effecting things outside of lovelace dashboards using card-mod would have been good (integration menus had the wrong z-index causing them to be un-clickable in some instances, side menu efected), a clue in a change log and/or if the update was pushed at April 1st as a clue instead of covertly several months ago might have caused less hair pulling. 

A option disable the seasonal effect (or perhaps an opt-in button), with an issue mention on midnight April 1st would have also been a good approach.

But nah I'm an entitled prick for being annoyed by an issue I didn't cause, couldn't quickly diagnose or resolve.

**Comment by Sholofly** [comment]
I see that it did harm some people, and for that Thomas said Sorry.  Maybe it's a misplaced joke but it shows that installing custom components can be risky, so that should be a valuable lesson out of this all.  But I can't agree with people that are picking on Thomas very hard now, he means a lot to this community,  never had bad intentions and he stated that he has learned a lesson. So upgrade if you don't like it, take some extra time to think about or, even better, contribute to extra review options in custom components, and move on. Happy April's fools day!

**Comment by Glc23** [comment]
That was AWSOME idea. Thank You

**Comment by ildar170975** [comment]
For me, it seemed ultimately as a 1st April joke when I saw it (although I already knew about this egg). Strange that some people did not get it and started complaining.

**Comment by Sholofly** [comment]
> For me, it seemed ultimately as a 1st April joke when I saw it (although I already knew about this egg). Strange that some people did not get it and started complaining.

Two reasons: 1) for some people it brought some functional issues. 2) People realize that authors of custom components can disturb their environment, although in this case it was an innocent joke. For me when I install a CC I trust the author. Some people's trust in Thomas or in custom components in general is damaged by this action.  That upsets people.

**Comment by SteveSharpe** [comment]
Put me in the category of "not funny".  It was ultimately harmless, but this is a popular maintainer of popular add-ons.  Everyone knows when they use free and open software there is some risk, but part of that risk is mitigated by popular software that is released by trusted maintainers.

This points out that basically nothing can be trusted.  Build up a popular free/open source product and gain credibility and then use that credibility to insert something damaging.  This one was ultimately not damaging, but it's a good reminder that trust of a platform like Home Assistant and its open community can be damaged pretty quickly.

**Comment by demolitions** [comment]
I lost almost an hour of work, and another half to recover my pc.

Since my laptop has huge GPU issues, freezes when chrome using hardware acceleration, and I forgot to disable it on the instance I use to connect to Home Assistant, since it has never been a problem.

Today I had it freeze on me multiple times, since like the moron I am, I set it up to open my home assistant dashboard at startup, and the CSS transform evidently uses hardware acceleration, so to solve it I had to login in text mode and purge my entire chrome user data directory, after I already lost the entire file I was working on.

Please avoid acting on other people's environments without warning.

And I thought it was pretty funny, too, when at first I saw the effect on my mobile.

**Comment by ildar170975** [comment]
@grastraa
I guess the issue may be closed?
