### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Mrsash2020** [thomasloven/lovelace-card-mod#256]
I am sure its me but no idea how to install. I am new to Homeassistant to bear with me.

 Sorry could not find the 'RAW' button to download unless firefox and edge hide it somewhere playing a cruel joke on me.

**Comment by jdtechsol** [comment]
@Mrsash2020, Your issue, as stated, is that you don't know what you are doing, which is fine, because we all have to start somewhere (I was literally in your shoes about 13 months go). Let me point you in the right direction. Please close this issue and refer to site for help: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744
