### ISSUE TITLE
Question: Media Queries

### ISSUE THREAD

**Issue by GerdRuetten** [thomasloven/lovelace-card-mod#258]
Hi all,

is it possible, to use card_mod with Media Queries?
If "yes", can somebody show an example please.

TIA

Gerd

**Comment by ildar170975** [comment]
1. Your issue is neither a bug nor a FR - it's a question. I suggest you to ask similar questions in a [HA Community dedicated card-mod thread](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/) and leave Github for bugs & FRs.
2. As for `mediaquery`: go to Community card-mod thread -> 1st post -> link at the bottom -> styles with mediaqueries

**Comment by GerdRuetten** [comment]
Sorry for my mistake!
I don't find the card-mod thread.
I will look there.
THX
