### ISSUE TITLE
Allow for styling of future elements

### ISSUE THREAD

**Issue by jdtechsol** [thomasloven/lovelace-card-mod#290]
Example: I can include styling for <ha-alert> but it will be ignored since the element does not exist until it is shown. Can we please allow for styling of future elements?

**Comment by ildar170975** [comment]
Please give a reproducible example.

**Comment by AINER** [comment]
Maybe I'm wrong, but it seems to me that they meant preliminary application of styles. Because when popups open or page reloads, styles are applied in real time, resulting in annoying jittery elements

https://github.com/thomasloven/lovelace-card-mod/assets/101467664/a356bcd1-3b3f-454c-b504-2f53a5fb7331

**Comment by ildar170975** [comment]
> resulting in annoying jittery elements

This is called "transition" and an expected behaviour since you have not disabled it.

**Comment by thomasloven** [comment]
It is possible. The DOM Navigation section of the readme explains how.
