### ISSUE TITLE
How would one reuse CSS? Missing info in docs

### ISSUE THREAD

**Issue by fusionstream** [thomasloven/lovelace-card-mod#410]
How does one reuse CSS? I saw someone had opened a ticket on this but it was closed without comment.

Presently, each temperature entity display has custom CSS that is conditional depending on the temperature reading. This has been replicated for each temperature entity. 

How would one go about reusing CSS to reduce code bloat?

**Comment by pcb1962** [comment]
This might be what you're looking for: https://www.home-assistant.io/docs/configuration/templating/#reusing-templates

For example, in custom_templates/pcbmacros.jinja I have this macro:
```
{% macro bool_red_blue(entity_id) %}
{% if is_state(entity_id,'True') %} red {% else %} royalblue {% endif %}
{% endmacro %}
```
which is called from a card_mod section like this:
<pre><code>  - entity: sensor.hall_presence
    card_mod:
      style: |
        :host {
          <b>{% from 'pcbmacros.jinja' import bool_red_blue %};</b>
          <b>color: {{ bool_red_blue(config.entity) }};</b>
        }
</code></pre>
Would be nice if the *color:* part could be included in the template so that a whole block of CSS could be put in one macro but I don't think that's possible, this at least saves duplicating the template code.

**Comment by ildar170975** [comment]
These questions should be asked on Community. 
This repo is for posting bugs and FRs.

**Comment by fusionstream** [comment]
You are right that it is a bit of a support question but I was hoping to sneak it in by way of this information being missing in the docs so that others might be able to find it ;) Thank you for your reply, I'll give it a go.

**Comment by ildar170975** [comment]
@fusionstream 
Find the main card-mod thread in Community. 
Within next week if I come back home I will add a tutorial about reusing card-mod code in that thread.

**Comment by ildar170975** [comment]
[Check here](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/7509?u=ildar_gabdullin)
